This notebook explores the Instacart **Online Grocery Shopping dataset**, a real-world e-commerce dataset containing millions of grocery orders, and prepares the data for building a product recommendation system.

In [45]:
import pandas as pd

In [46]:
orders = pd.read_csv("../data/raw/orders.csv")
order_products = pd.read_csv("../data/raw/order_products__prior.csv")
products = pd.read_csv("../data/raw/products.csv")

In [47]:
orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [48]:
order_products.head()

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [49]:
products.head()

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

In [50]:
orders.shape

(3421083, 7)

In [51]:
order_products.shape

(32434489, 4)

In [52]:
products.shape

(49688, 4)

## Dataset size
The order_products_prior table contains over 30 milion rows, whitch can slow down exploratory analysis and experimentation.

To make development faster, a random subset of the dataset is used during the initial stages of the project.

Using a sample allows for:
- faster experimentation and debugging
- lower memory usage
- preserving the overall data distribution through random sampling

The full dataset can later be used for final model training if needed.

Sample size used in this notebook: 200 000 rows.

In [53]:
order_products = order_products.merge(
    products[['product_id', 'product_name']],
    on='product_id'
)

In [54]:
order_products.head()

   order_id  product_id  add_to_cart_order  reordered           product_name
0         2       33120                  1          1     Organic Egg Whites
1         2       28985                  2          1  Michigan Organic Kale
2         2        9327                  3          0          Garlic Powder
3         2       45918                  4          1         Coconut Butter
4         2       30035                  5          0      Natural Sweetener

In [55]:
order_products.columns

Index(['order_id', 'product_id', 'add_to_cart_order', 'reordered',
       'product_name'],
      dtype='str')

In [56]:
order_products_sample = order_products.sample(n=200000, random_state=42)

In [57]:
order_products_sample.head()

,order_id,product_id,add_to_cart_order,reordered,product_name
29481110,3109255,34099,16,0,Crushed Red Chili Pepper
2852353,301098,41950,5,0,Organic Tomato Cluster
11194500,1181866,45066,8,0,Honeycrisp Apple
15909397,1678630,8859,2,1,Natural Spring Water
6101870,644090,24781,2,0,"PODS Laundry Detergent, Ocean Mist Designed fo..."

In [58]:
order_products_sample.info()

<class 'pandas.DataFrame'>
Index: 200000 entries, 29481110 to 10928200
Data columns (total 5 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   order_id           200000 non-null  int64
 1   product_id         200000 non-null  int64
 2   add_to_cart_order  200000 non-null  int64
 3   reordered          200000 non-null  int64
 4   product_name       200000 non-null  str
dtypes: int64(4), str(1)
memory usage: 9.2 MB

In [59]:
order_products_sample.shape

(200000, 5)

In [60]:
order_products_sample['product_name'].value_counts().head(10)

product_name
Banana                    2976
Bag of Organic Bananas    2333
Organic Strawberries      1668
Organic Baby Spinach      1489
Organic Hass Avocado      1301
Organic Avocado           1081
Large Lemon                917
Organic Raspberries        901
Strawberries               862
Organic Whole Milk         853
Name: count, dtype: int64

In [61]:
order_products_sample.groupby("order_id")["product_name"].apply(list).head()

order_id
61                            [0% Greek Strained Yogurt]
66     [Organic Lightly Salted Sea Salt Thin & Crispy...
71                                [Organic Hass Avocado]
74                          [Organic Chicken Bone Broth]
107                           [Apple & Cherry Fruit Bar]
Name: product_name, dtype: object

### **Processed dataset**
After merging product information and sampling the data, a processed dataset was created containing the following fields:
- order_id,
- product_id,
- add_to_cart_order,
- reordered,
- product_name.

This dataset will serve as the input for building the recommendation system.

In [62]:
order_products_sample.to_csv("../data/processed/transactions_sample.csv", index=False)